# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="ic2c_json_crops"
version="${version}"
displayName="IC2C Json Crops"
credits="The ExampleMod dev team"
authors="Trinsdar"
description='''
Utility mod for maing ic2c crops using json.
'''
[[dependencies.ic2c_json_crops]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ic2c_json_crops]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
